trigger:
- master

pool:
  name: 'default'
  vmImage: 'ubuntu-latest'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'  # Specify the JDK version you need
    jdkArchitecture: 'x64'  # Specify architecture if needed
    checkLatest: true  # Ensure you get the latest patch version

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'  # Match the version specified in JavaToolInstaller
    jdkArchitectureOption: 'x64'  # Specify architecture if needed
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
